### ISSUE TITLE
Toggle Menu button does nothing

### ISSUE THREAD

**Issue by Noxxys** [driftyco/ionic-unit-testing-example#15]
It's not related to unit testing, but the 'Toggle Menu' button does nothing when clicked, both with ionic serve and the Android emulator.

I don't have this problem with the original app, created with `ionic start myApp sidemenu --v2`
I just did `npm install` after cloning this repo. Which steps am I missing?

**Comment by leifwells** [comment]
The menu button that should appear in the upper left is also missing, at least for me.

Why are there so many weird problems with this project?

**Comment by leifwells** [comment]
Current `src/app/app.html`:

```
<ion-nav [root]="rootPage"></ion-nav>
```

What `src/app/app.html` looks like in a normal app created using `ionic start myApp sidemenu --v2`:

```
<ion-menu [content]="content">
  <ion-header>
    <ion-toolbar>
      <ion-title>Menu</ion-title>
    </ion-toolbar>
  </ion-header>

  <ion-content>
    <ion-list>
      <button menuClose ion-item *ngFor="let p of pages" (click)="openPage(p)">
        {{p.title}}
      </button>
    </ion-list>
  </ion-content>

</ion-menu>

<ion-nav [root]="rootPage" #content swipeBackEnabled="false"></ion-nav>
```

I wonder what happened?

**Comment by leifwells** [comment]
I've made a pull request:
https://github.com/driftyco/ionic-unit-testing-example/pull/18

**Comment by GeorgeAnagnostopoulos** [comment]
If you add the required markup in app.html as per seed project everything works fine.

**Comment by leifwells** [comment]
Fixed with https://github.com/driftyco/ionic-unit-testing-example/pull/18
