### ISSUE TITLE
Ionic 3 support

### ISSUE THREAD

**Issue by neilbo** [driftyco/ionic-unit-testing-example#27]
I had an existing Ionic 2.4.8, and followed the tutorial by @roblouie to add unit tests.
Which worked great.

I'm in the process of upgrading to Ionic 3, using the [ChangeLog Steps](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade).

I've followed it, step by step but unit tests are now broken.

I see you have a [pull request](https://github.com/driftyco/ionic-unit-testing-example/pull/26) by @MTechDE. 

Is this master branch going to work with ionic 3.x? I can't find the branch for ionic 3 package.json version and file changes.

**Comment by leifwells** [comment]
Can you show us an error? 

I had a similar experience (but only with one of my spec files) where I was receiving a fairly vague error:
```
Uncaught TypeError: Cannot read property 'links' of null thrown
	Expected undefined to equal 0.
```

With a little searching, I found an example where I had to change a line in my spec from this
```
imports: [
        IonicModule.forRoot(MyPage)
 ],
```
to this:
```
imports: [
        IonicModule.forRoot(WalkthroughPage, {}, { links: [] })
],
```

The fact that I only needed to make this change in one of my specs disturbs me, but this is an example of changes in Ionic v3 that may effect you.

**Comment by spiraljacobs** [comment]
As above, I updated my app to ionic 3, set up the pages for lazy loading, and broke all my page tests.  No idea how to set up tests to support Ionic 3 and lazy loadable pages now.  Any help/updated code for lazy loadable pages being testable would be super helpful.

**Comment by danielsogl** [comment]
Check out the updated docs: https://ionicframework.com/docs/resources/ng2-translate/

**Comment by spiraljacobs** [comment]
@danielsogl doesn't really help with an example of testing pages w/ Ionic 3.  We need an updated version of this repo for Ionic 3 to show how to use Angular test bed w/ Ionic 3 pages and any potential issues around lazy loading.

**Comment by spiraljacobs** [comment]
@danielsogl cloning your fork - hope it helps!
