### ISSUE TITLE
References

### ISSUE THREAD

**Issue by lathonez** [driftyco/ionic-unit-testing-example#5]
Hey All,

Thanks a lot for getting around to this. I can finally deprecate https://github.com/lathonez/clicker, which I plan on doing immediately. It's certainly been a long time coming but I'm glad it's here :)

> Based on Josh Morony's excellent Unit Testing guides and sample app.

Josh's guides are amazing - much better than anything I could put together. As Josh's write-ups and sample app are based on clicker (he kindly references me here: https://www.joshmorony.com/introduction-to-testing-ionic-2-applications-with-testbed/), I expected to be mentioned here in a similar fashion.

One of my first users, @BugsBunnyBR raised a PR https://github.com/driftyco/ionic/issues/5579 in February 2016 to merge Clicker into ionic-app-base. This PR is still open against ionic-app-scripts (and I still contribute to it) on https://github.com/driftyco/ionic-app-scripts/issues/687.

https://github.com/lathonez/clicker/commit/7b1a80c in October 2016 is the first example of an Ionic App leveraging angular/cli for testing (very happy to be corrected on this) - which this repo is ultimately based on.

I've also kept a pretty comprehensive changelog if you're interested: https://github.com/lathonez/clicker/blob/master/CHANGELOG.md 

If you need further convincing, compare your `src/mocks.ts` with mine 😉 

References aside, thanks for the fantastic work you've done with Ionic 2. For me the introduction of this repository makes the framework complete.

Thanks,

Stephen

**Comment by masimplo** [comment]
As an early adopter of Ionic2 and testing since almost day 1, I understand that Josh Morony brought this to light, but @lathonez has been single handily supporting everyone writing tests for Ionic2 up to this day and keeping his repo up to day with every release of Ionic2 ever since. 
I believe that special reference for his efforts is in order.

**Comment by mlynch** [comment]
Thanks guys. I updated the blog post to give a shout out: http://blog.ionic.io/basic-unit-testing-in-ionic/ 

I actually just replaced this entire project with one inspired by [https://github.com/roblouie/unit-testing-demo](https://github.com/roblouie/unit-testing-demo) which removes a lot of dependencies, including the Angular CLI.
