### ISSUE TITLE
node_modules/@types/jasmine/index.d.ts getting picked up by TypeScript compiler

### ISSUE THREAD

**Issue by kamok** [driftyco/ionic-unit-testing-example#6]
I just cloned this app and tried to `ionic serve` after `npm install`. A bunch of TypeScript errors from node_modules/@types/jasmine/index.d.ts came up. Eventhough `ts.config` has a   
```
"exclude": [
    "node_modules",
    "src/**/*.spec.ts"
],
```
it was still looking there. 

To fix this, set @types/jasmine": "2.5.38".

To see more: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14569

**Comment by satbirjhuti** [comment]
The solution that worked for me was to use typescript @ 2.1.6

**Comment by satbirjhuti** [comment]
Upgrading typescript@2.1.6 from 2.0.9  fixed this issue for me.

**Comment by kamok** [comment]
@satbirjhuti I think that is the better solution. Good find. It works for me.

**Comment by lathonez** [comment]
This shouldn't be closed - we need that fix in package.json.

**Comment by lathonez** [comment]
https://github.com/driftyco/ionic-unit-testing-example/pull/7

**Comment by kamok** [comment]
@lathonez Sorry friend; was going to make a PR but I forgot. But good thing you found this Issue. =)

**Comment by GeorgeAnagnostopoulos** [comment]
TypeScript v2.2.1 also works!

**Comment by lathonez** [comment]
Any updates on this (or any of the other issues / PRs that have been raised since this repo was created)?

It would be cool to get an honest appraisal of the kind of support we're going to get here, so we can make an informed decision on whether we should be using it or not.

Thanks

**Comment by kamok** [comment]
No. From looks of it nobody from Ionic has touched the repo since it was first created. I thought you had definitive information from the Ionic team that they were to invest resources for this endeavor, but I'll get in touch with one of them on the Ionic Slack channel and see what goes, on Monday.

**Comment by kamok** [comment]
@lathonez 
Me: 

> Can anyone from the Ionic Team explain the level of support that would be given for https://github.com/driftyco/ionic-unit-testing-example  repo? There's an active community on it, and multiple seeder test projects that are looking to migrate to it. Are we getting official support?

Ionic:
> it's an example repo
> once the actual testing process has been moved into app-scripts/CLI, it will no longer be needed

**Comment by lathonez** [comment]
> once the actual testing process has been moved into app-scripts/CLI, it will no longer be needed

Is there a github issue tracking this?
