### ISSUE TITLE
Generators are only available for Ionic 2 projects (CLI v2.2.1)

### ISSUE THREAD

**Issue by kamok** [driftyco/ionic-unit-testing-example#8]
When doing: 

`ionic generate component settings-menu`

You get this error:
```
Generators are only available for Ionic 2 projects (CLI v2.2.1)

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```
Any generate commands seem to yield the same thing.

**Comment by gianpaj** [comment]
I think it's because this is missing in the `ionic.config.json` file:
```json
  "v2": true,
```

**Comment by kamok** [comment]
Mmm I see it's also missing  `"typescript": true`. Does that affect anything as well? I'm going to make a PR.

**Comment by leifwells** [comment]
Fixed with https://github.com/bfassbender/ionic-unit-testing-example/pull/3
